[package]
name = "cactus"
description = "Immutable cactus stack"
repository = "https://github.com/softdevteam/cactus/"
version = "1.0.2"
authors = ["Laurence Tratt <laurie@tratt.net>"]
readme = "README.md"
license-file = "LICENSE"
categories = ["data-structures"]

[lib]
name = "cactus"
