[package]
name = "cactus"
description = "Immutable cactus stack"
repository = "https://github.com/softdevteam/cactus/"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
license = "UPL-1.0"

[lib]
name = "cactus"
